name: Develop-Premerge

on:
  pull_request:
    branches:
      - develop

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR branch
        id: code_build
        run: |
          echo "PR branch is ${{ github.head_ref }}"
          if [[ ! "${{ github.head_ref }}" =~ ^feature/ ]]; then
            echo "This PR is not from a feature branch."
            exit 1
          fi

      - name: Install SSH Client and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass

      - name: Trigger Jenkins Job
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "java -jar /path/to/jenkins-cli.jar -s http://localhost:8080/jenkins build hello-world-backend-premerge"
